version: '2.1'
orbs:
  nodejs: canterberry/nodejs@12.1.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
workflows:
    example-workflow:
      jobs:
        - nodejs/install
